production:
  domain:
    name: "bricks@bricksites.info"
    ssh_options: "-p 2222"
  deploy_to: "~/public_html/micah/brickcaster"
  repository: "git@github.com:micahredding/brickcaster.git"
  branch: "static"
